config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords'
      }

  root to: 'welcome#index', via: [:get, :post]
  match 'param_entry', to: 'welcome#param_inputs', via: [:get, :post]

  match 'contact', to: 'static_pages#contact', via: 'get'
  match 'project_overview', to: 'static_pages#project_overview', via: 'get'
  match 'data_release', to: 'static_pages#data_release', via: 'get'
  match 'user_signup', to: 'static_pages#user_signup', via: 'get'

  match 'study_query', to: 'study_queries#index', via: [:get, :post]
  match 'study_explore', to: 'explore_studies#index', via: [:get, :post]

  match 'gene_summary', to: 'gene_summaries#index', via: [:get, :post]

  match 'neoantigen_query', to: 'neoantigen_queries#index', via: [:get, :post]

  match 'sample_query', to: 'sample_queries#index', via: [:get, :post]
  get 'get_gene_expr_data', to: 'sample_queries#get_gene_expr_data'

  

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if !login_required or user_signed_in?
      #@grouped_cancer_studies = CancerType.cancer_study_dropdown
      @grouped_cancer_studies = CancerStudy.study_dropdown
      render :index
    else
      redirect_to '/users/sign_in'
    end
  end

  def param_inputs
    @query_type = params[:element_id]
    if @query_type == 'target_patient'
      @patient_nrs = Patient.populate_dropdown_grouped(params[:studies])
    elsif @query_type == 'target_neoantigen'
      @hla_types = SampleHlaBinding.hla_dropdown
    end
    respond_to do |format|
      format.js
    end
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper

end

app/views/welcome/_example_query_gcr.html.erb
<div style="background-color: lightgrey">
  <div class="container container-sidebar">
    <div class="row">
      <span class = "badge badge-sidebar" style="margin-bottom: 1px;">Example queries</span>
    </div>
    <div class="row">
      <span class = "badge badge-sidebar-subhead" style="margin-bottom: 18px; border-top: 2px solid black;"><i class="custom-icons"> <%= image_tag(Portal::Config::Info['pie_image_example'], width:"25") %></i> Explore Study: </span>
    </div>
    <div>
      <ul style="margin-top: -24px; margin-left: -20px; font-size: 15px;">
        <li style="margin-bottom: 3px;">What is the age distribution of patients in the GCR STAD study?</li>
        <li style="margin-bottom: 3px;">How many GCR STAD patients have an <i>FGFR2</i> amplification?</li>
        <li style="margin-bottom: 3px;">What immune cell types are enriched in GCR STAD patients?</li>
        <li style="margin-bottom: 3px;">What is the proportion of bacterial types in the microbiomes of GCR STAD patients?</li>
      </ul>
    </div>

    <div class="row">
      <span class = "badge badge-sidebar-subhead" style="margin-bottom: 18px; border-top: 2px solid black;"> <i class="custom-icons"> <%= image_tag(Portal::Config::Info['gene_image_example'], width:"23") %></i> Gene Query:</span>
    </div>
    <div>
      <ul style="margin-top: -24px; margin-left: -20px; font-size: 15px;">
        <li style="margin-bottom: 3px;">How many TCGA STAD patients have a missense mutation in <i>TP53?</i></li>
        <li style="margin-bottom: 3px;">How does the proportion of <i>KRAS</i> mutations compare between GCR and TCGA STAD studies?</li>
      </ul>
    </div>

    <div class="row">
      <span class = "badge badge-sidebar-subhead" style="margin-bottom: 18px; border-top: 2px solid black;"> <i class="custom-icons"> <%= image_tag(Portal::Config::Info['hla_image_example'], width:"23") %></i> Neoantigen/HLA Query: </span>
    </div>
    <div>
      <ul style="margin-top: -24px; margin-left: -20px; font-size: 15px;">
        <li style="margin-bottom: 3px;">Are there any GCR STAD patients with neoantigens that have a strong binding affinity to their own HLA type?</li>
      </ul>
    </div>

    <div class="row">
      <span class = "badge badge-sidebar-subhead" style="margin-bottom: 18px; border-top: 2px solid black;"><i class="custom-icons"> <%= image_tag(Portal::Config::Info['patient_image_example'], width:"23") %></i> Patient Query: </span>
    </div>
    <div>
      <ul style="margin-top: -24px; margin-left: -20px; font-size: 15px;">
        <li style="margin-bottom: 3px;">Show me all available data for GCR STAD patient: P04846.</li>
      </ul>
    </div>

  </div>

</div>

app/views/welcome/_example_query_ipg.html.erb
<div style="background-color: lightgrey">
  <div class="container container-sidebar">
    <div class="row">
      <span class = "badge badge-sidebar" style="margin-bottom: 1px;">Example queries</span>
    </div>
    <div class="row">
      <span class = "badge badge-sidebar-subhead" style="margin-bottom: 18px; border-top: 2px solid black;"><i class="custom-icons"> <%= image_tag(Portal::Config::Info['pie_image_example'], width:"25") %></i> Explore Study: </span>
    </div>
    <div>
      <ul style="margin-top: -24px; margin-left: -20px; font-size: 15px;">
        <li style="margin-bottom: 3px;">What is the age distribution of patients in the IMH COAD study?</li>
        <li style="margin-bottom: 3px;">How many IMH COAD patients have an <i>FGFR2</i> amplification?</li>
        <li style="margin-bottom: 3px;">What immune cell types are enriched in IMH COAD patients?</li>
        <li style="margin-bottom: 3px;">What is the proportion of bacterial types in the microbiomes of IMH COAD patients?</li>
      </ul>
    </div>

    <div class="row">
      <span class = "badge badge-sidebar-subhead" style="margin-bottom: 18px; border-top: 2px solid black;"> <i class="custom-icons"> <%= image_tag(Portal::Config::Info['gene_image_example'], width:"23") %></i> Gene Query:</span>
    </div>
    <div>
      <ul style="margin-top: -24px; margin-left: -20px; font-size: 15px;">
        <li style="margin-bottom: 3px;">How many TCGA STAD patients have a missense mutation in <i>TP53?</i></li>
        <li style="margin-bottom: 3px;">How does the proportion of <i>KRAS</i> mutations compare between IMH and TCGA COAD studies?</li>
      </ul>
    </div>

    <div class="row">
      <span class = "badge badge-sidebar-subhead" style="margin-bottom: 18px; border-top: 2px solid black;"> <i class="custom-icons"> <%= image_tag(Portal::Config::Info['hla_image_example'], width:"23") %></i> Neoantigen/HLA Query: </span>
    </div>
    <div>
      <ul style="margin-top: -24px; margin-left: -20px; font-size: 15px;">
        <li style="margin-bottom: 3px;">Are there any IMH COAD patients with neoantigens that have a strong binding affinity to their own HLA type?</li>
      </ul>
    </div>

    <div class="row">
      <span class = "badge badge-sidebar-subhead" style="margin-bottom: 18px; border-top: 2px solid black;"><i class="custom-icons"> <%= image_tag(Portal::Config::Info['patient_image_example'], width:"23") %></i> Patient Query: </span>
    </div>
    <div>
      <ul style="margin-top: -24px; margin-left: -20px; font-size: 15px;">
        <li style="margin-bottom: 3px;">Show me all available data for IMH COAD patient: CRC-002.</li>
      </ul>
    </div>

  </div>

</div>

app/views/welcome/_param_select.html.erb
<% if @query_type == 'target_patient' %>
  <% if @patient_nrs.empty? %>
        <%= text_field(:query_params, :error, class: 'form-control box-text', disabled: true, placeholder: 'Select a study/studies first') %>
  <% else %>
        <%= select(:query_params, :patient_id, grouped_options_for_select(@patient_nrs), {prompt: 'Select Patient'},
             class: 'form-control box-text selectpicker') %>
  <% end %>
<% elsif @query_type == 'target_neoantigen' %>
  <%= select(:query_params, :neoantigen, @hla_types, {prompt: 'Select HLA'},
             class: 'form-control box-text selectpicker', 'data-live-search': 'true') %>
<% elsif @query_type == 'target_gene' %>
  <%= text_field(:query_params, :gene_name, class: 'form-control box-text',
                 placeholder: 'Enter Gene(s)') %>
<% end %>

app/views/welcome/_study_query_form.html.erb
<div class="panel-body">
  <%= form_tag study_query_path, id: 'study_query_form', method: 'get', class: 'text-left' do %>
   <div class="container">
      <div class="row">
        <div class="col-md-8" style="height: 100%;">
          <div class="row">
            <div class="col-md-12">
              <div class="container container-border">
                <div class="row">
                  <span class = "badge badge-header" style="margin-bottom: 28px;">Select study/studies to query:</span>
                </div>
                <div>
                  <%= content_tag :div, '', id: 'study_error', class: 'alert alert-danger center-block text-center align-middle', style: 'font-size: 20px; display:none;'%>
                </div>
                <div class="table-responsive">
                  <table class='table table-borderless table-condensed table-checkboxes' style="width:100%; margin:auto; font-size: 20px;  border-collapse: separate; border-spacing: 10px 0px; table-layout:fixed;">


                    <tr>
                      <td colspan="2" style="vertical-align: middle;">
                        <div class="pretty p-icon">
                          <input type="checkbox" id="selectAll" value="selectAll" />
                          <div class="state">
                            <%= content_tag(:i, "check", class: "icon mi mi-check") %>
                            <label style="padding-left: 8px;">Select/Deselect All</label>
                          </div>
                        </div>
                      </td>
                    </tr>
                    <% @grouped_cancer_studies.each do |ctype| %>
                      <tr style="font-weight: bold; ">
                        <td colspan="2" style="padding-top: 10px;"><%= ctype[0] %></td>
                      </tr>
                      <% ctype[1].each do |subtype| %>
                        <tr style="padding-top: 0;">
                          <td style="width: 1px;">
                            <div class="pretty p-icon">
                              <input type="checkbox" class="checkbox-study" value=<%= subtype[1] %>[] name="cancer_studies[]"/>
                              <div class="state">
                                <%= content_tag(:i, "check", class: "icon mi mi-check") %>
                                <label style="padding-left: 8px;"><%= subtype[0] %></label>
                              </div>
                            </div>
                          </td>
                          <td style="text-align: right; vertical-align: middle;">
                            <label style="font-style: italic; font-weight: normal; font-size: 19px; text-align: right; color: gray; margin-right: 5px;";><%= subtype[2].to_s.concat(' samples') %></label>

                            <button type="submit" class="explore_query btn-explore btn btn-labeled text-center tip-container" data-toggle="popover" data-trigger="hover" data-content="Explore <%= ctype[0] %> <%= subtype[0] %> study" value="<%= subtype[1] %>" name="cancer_studies" >
                              <span class="btn-label-explore pull-left" style="margin-left: -11px;"><i> <%= image_tag(Portal::Config::Info['pie_image'], width:"25") %></i></span>
                              <span style="margin-top:3px; margin-left: 28px; display: block; font-size: 17px;">Explore Study</span>
                            </button>
                          </td>
                        </tr>
                      <% end %>
                    <% end %>
                    <tr>
                      <td style="padding-bottom: 20px;"></td>
                    </tr>
                  </table>
                </div>
              </div> <!-- /container-border (left panel) -->
            </div><!-- /col-md-6 (left panel) -->
          </div>

          <div class="row">
            <div class="col-md-12" style="height:100%;">
              <div class="container container-border" style="height:100%;">
                <div class="row">
                  <span class = "badge badge-header" style="margin-bottom: 11px;">Query the study/studies by:</span>
                </div>

                <div class="table-responsive">
                  <table class='table table-borderless table-condensed table-radio' style="width:100%; margin:auto; border-collapse: separate; border-spacing: 10px 6px; font-size: 20px; max-width: 600px;">
                    <tr style="margin-top:30px">

                      <td style="vertical-align: middle; width: 10px;">
                        <button type="button" class="btn-query btn radio-label btn-labeled tip-container" id="target_gene" data-placement="left" data-content="Click here to query selected studies by Gene">
                          <span class="btn-label pull-left" style="margin-left: -11px;"><i class="custom-icons"> <%= image_tag("gene_white.png", width:"30") %></i></span>
                          <span style="margin-top:4px;display: block;">Gene</span>
                        </button>
                      </td>
                      <td style="vertical-align: middle; text-align: center;">
                        OR
                      </td>
                      <td style="vertical-align: middle; width: 10px;">
                        <button type="button" class="btn-query btn radio-label btn-labeled tip-container" id="target_neoantigen" data-placement="left" data-content="Click here to query selected studies by Neoantigen/HLA">
                          <span class="btn-label pull-left" style="margin-left: -11px;"><i class="custom-icons"> <%= image_tag("neoantigen_white.png", width:"30") %></i></span>
                          <span style="margin-top:4px;display: block;">Neoantigen</span>
                        </button>
                      </td>
                      <td style="vertical-align: middle; text-align: center;">
                        OR
                      </td>
                      <td style="vertical-align: middle; width: 10px;">
                        <button type="button" class="btn-query btn radio-label btn-labeled tip-container" id="target_patient" data-placement="left" data-content="Click here to query by patient">
                          <span class="btn-label pull-left" style="margin-left: -11px;"><i class="custom-icons"> <%= image_tag("patient.png", width:"30") %></i></span>
                          <span style="margin-top:4px;display: block;">Patient</span>
                        </button>
                      </td>
                    </tr>


                    <tr>
                      <td></td>
                      <td id="param_select" class="box-align" align="center" colspan="3">
                      </td>
                      <td></td>
                    </tr>


                    <tr style="height: 5px;">
                    </tr>
                  </table>
                </div>
              </div> <!-- /container-border (right panel) -->

              <div>
                <%= content_tag :div, '', id: 'blank_param_error', class: 'alert alert-danger center-block text-center align-middle', style: 'font-size: 20px; display:none;'%>
              </div>
              <% if flash[:error] %>
                <div id='invalid_param_error' class="alert alert-danger center-block text-center align-middle" style="font-size: 20px;">
                  <%= flash[:error] %>
                </div>
              <% end %>

              <div style="text-align: center;">
                <%= submit_tag "Submit Query", id: "submit_query", style: "font-weight: bold; font-size: 23px; margin-top: 20px; margin-bottom: 20px;", class: "btn btn-primary btn-md btn-submit" %>
              </div>
            </div> <!-- /col-md-6 (right panel) -->
          </div>
        </div> <!-- /panel-body row -->

        <div class="col-md-4" style="height: 620px;">
          <%= render "example_query_#{Portal::Config::Info['project']}" %>
        </div>

      </div>
    </div> <!-- /panel-body container -->
    <% end %><!-- /form tag for outcome summary -->
</div> <!-- /panel body -->

<script>
    $(function () {
        $('[data-toggle="popover"]').popover();
    })
</script>

app/views/welcome/index.html.erb
<div class="container-fluid" align="center">
  <%= image_tag(Portal::Config::Info['welcome_image'], class: "img-responsive", style: 'height:100px; margin-top: -15px;') %>
</div>

<div class="container-fluid h3" align="center" style="margin-top:5px;margin-bottom:20px">
  <%= Portal::Config::Info['main_title'] %>
</div>
<div class="container container-fluid">
  <div class="row"><!-- row 1 --> 
    <div class="col-md-12">

      <div class="panel">
        <div class="panel-body">
          <%= render 'study_query_form' %>
        </div><!-- /panel body -->
      </div><!-- /panel -->

    </div><!-- /col-->

    <p class="info"></p>
  </div><!-- /row 1-->

</div>

app/views/welcome/index_maint.html.erb
<div class="center jumbotron">
  <div class="panel panel-info">
    <div class="panel-body">
      <h2>The Stanford-TCGA Portal: An Interactive Web Interface for Exploring the Clinical Phenotypic Relevance of Specific Cancer Drivers</h2>
    </div><!-- /panel body -->
  </div><!-- /panel -->
  <div class="row"><!-- row 1 -->
    
        <div class="panel-body">
        <p style="color:red;font-weight:bold;font-size:150%">System is down for Maintenance</p>
        <p style="color:red;font-weight:bold;font-size:150%">Expected completion Monday 6/15 </p>
        </div><!-- /panel body -->
      
  </div><!-- /row 1-->
</div><!-- /jumbotron -->

app/views/welcome/param_inputs.js.erb
$("#param_select").html("<%= j render(partial: 'param_select') %>");