config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords'
      }

  root to: 'welcome#index', via: [:get, :post]
  match 'param_entry', to: 'welcome#param_inputs', via: [:get, :post]

  match 'contact', to: 'static_pages#contact', via: 'get'
  match 'project_overview', to: 'static_pages#project_overview', via: 'get'
  match 'data_release', to: 'static_pages#data_release', via: 'get'
  match 'user_signup', to: 'static_pages#user_signup', via: 'get'

  match 'study_query', to: 'study_queries#index', via: [:get, :post]
  match 'study_explore', to: 'explore_studies#index', via: [:get, :post]

  match 'gene_summary', to: 'gene_summaries#index', via: [:get, :post]

  match 'neoantigen_query', to: 'neoantigen_queries#index', via: [:get, :post]

  match 'sample_query', to: 'sample_queries#index', via: [:get, :post]
  get 'get_gene_expr_data', to: 'sample_queries#get_gene_expr_data'

  

end

app/controllers/explore_studies_controller.rb
class ExploreStudiesController < ApplicationController
  include ApplicationHelper
  include Statistics
  before_action :authenticate_user!, if: :login_required

  def index
    num_cancers = 1
    @cancer_study_id = params[:cancer_studies]
    @selected_study = CancerStudy.where({id: @cancer_study_id}).first
    @cancer = @selected_study.study_name
    @num_samples = @selected_study.total_samples
    @total_mut_samples = @selected_study.num_mut_samples
    @total_cn_samples = @selected_study.num_cn_samples
    @study_fmt = (['TCGA', 'GCR'].include?(@selected_study.study) ? @selected_study.study.downcase : 'ipg')

    # For gene summary tab
    gene_info = GeneSummary.includes(:gene).references(:gene).where({cancer_study_id: @cancer_study_id})
    if num_cancers == 1  #Leaving code here for multiple cancers in case we want to include option at some point
      @gene_mutations = gene_info.where("tot_mut_sample > 0 OR genes.cancer_assoc = 'Y'")
                          .order('tot_mut_sample DESC')
                          .pluck(:mut_rank, :gene_name, 'genes.cancer_assoc', 'genes.cytoband', 'genes.oncogene', 'genes.tumor_suppressor',
                                 :tot_mut_sample)
      @gene_cnvs = gene_info.where("tot_cnv_sample > 0 OR genes.cancer_assoc = 'Y'")
                         .order('tot_cnv_sample DESC')
                         .pluck(:cnv_rank, :gene_name, 'genes.cancer_assoc', 'genes.cytoband', 'genes.oncogene', 'genes.tumor_suppressor',
                                :tot_cnv_sample, :num_amp_sample, :num_del_sample)

      # Determine cutoff for 'top' genes and CNVs (>10% or >1 sample, or ># samples of 100th gene in rank order)
      mut_sample_cutoff = top_gene_threshold(@selected_study.num_mut_samples, @gene_mutations[99][6])
      cnv_sample_cutoff = top_gene_threshold(@selected_study.num_cn_samples, @gene_cnvs[99][6])
      @top_gene_thresholds = [mut_sample_cutoff, @selected_study.num_mut_samples,
                              cnv_sample_cutoff, @selected_study.num_cn_samples]
      @gene_mutations.select! {|g| (g[6] >= mut_sample_cutoff || g[2] == 'Y')}
      @gene_cnvs.select! {|g| (g[6] >= cnv_sample_cutoff || g[2] == 'Y')}

    else
      gene_mut_totals = gene_info.group(:gene_name)
                            .pluck(:mut_rank, :gene_name, 'genes.cancer_assoc', 'genes.cytoband', 'genes.oncogene', 'genes.tumor_suppressor',
                                   'SUM(tot_mut_sample)')
      gene_cnv_totals = gene_info.group(:gene_name)
                            .pluck(:cnv_rank, :gene_name, 'genes.cancer_assoc', 'genes.cytoband', 'genes.oncogene', 'genes.tumor_suppressor',
                                   'SUM(tot_cnv_sample)', 'SUM(num_amp_sample)', 'SUM(num_del_sample)')
      @gene_mutations = gene_mut_totals.sort_by {|k| k[6]}.reverse.first(25)
      @gene_cnvs = gene_cnv_totals.sort_by{|k| k[6]}.reverse.first(25)
    end

    # For clinical tab
    patient_obj = Patient.where({cancer_study_id: @cancer_study_id})
    patient_info = patient_obj.to_a
    @gender_counts = format_for_pie(patient_info, 'gender')
    @smoking_counts = format_for_pie(patient_info, 'smoking_history')
    @ages = patient_info.map {|pt| pt[:dx_age].to_i if pt[:dx_age] != 'NA'}.compact
    #IPG only, except site_counts for TCGA also:
    @site_counts = format_for_pie(patient_info, 'cancer_site')
    @stage_counts = format_for_pie(patient_info, 'summary_stage')
    #GCR only, except race_ethnicity for TCGA also
    @race_counts = format_for_pie(patient_info, 'race_ethnicity')
    @family_history_cts = patient_obj.group_by {|p| p.gc_history}.sort.map{|key, val| {name: key, y: val.size}}
    @site_dtl_counts = group_for_pie(patient_info, 'cancer_site_dtl')
    @diagnosis_counts = format_for_pie(patient_info, 'diagnosis','N')
    @diagnosis_dtl_counts = group_for_pie(patient_info, 'diagnosis_subtype')
    @differentiation_cts = format_for_pie(patient_info, 'differentiation')
    #TCGA only:
    @survival_mths = patient_info.map {|pt| (pt[:days_survival]/12.0).round(0).to_i if !pt[:days_survival].nil? }.compact
    @bmi = patient_info.map {|pt| pt[:dx_bmi].to_f.round(1) if pt[:dx_bmi] != 'NA'}.compact

    # Patient clinical table
    @patient_data = patient_info

    # Samples/sequencing table
    @cohort_samples = CohortSample.where({cancer_study_id: @cancer_study_id})
                      .order(:patient_nr, :sample_nr).to_a

    # For microbiome tab
    mbiome_info = SampleTaxonomy.includes(:sample).references(:sample)
                       .where({cancer_study_id: @cancer_study_id, taxonomy_level: 1})
                       .order(:patient_nr, :sample_type).to_a
    mbiome_sample_keys = mbiome_info.collect{|rec| [rec.patient_nr, rec.sample_type, rec.sample_id, rec.sample.patient_id]}.uniq
    bacteria_totals = SampleTaxonomy.sample_bacteria_rds(@cancer_study_id)

    @mbiome_perc = []; @mbiome_colors = [];
    phylum_names = SampleTaxonomy.all_phylum(@cancer_study_id)

    for phylum in phylum_names
      mbiome_data = []
      #phylum_color_idx = Hash[Phylum::COLOR_INDICES.map{|k,v| [k.sub(/ \((\d+)\)/,''), v]}]
      #cidx = phylum_color_idx[phylum[3..-1]]
      cidx = Phylum::COLOR_INDICES[phylum[3..-1]]
      @mbiome_colors.push(PlotInfo::PLOT_COLORS[:multi_20][cidx-1])
      phylum_data = mbiome_info.select{|mb| mb[:taxo_name] == phylum}
      for sample in mbiome_sample_keys
        sample_phylum = phylum_data.select{|pd| pd[:patient_nr] == sample[0] and pd[:sample_type] == sample[1]}
        mbiome_data.push(sample_phylum.empty? ? 0 : format_pct(sample_phylum[0][:read_cts], bacteria_totals[sample[2]],2))
      end
      @mbiome_perc.push({name: phylum[3..-1], data: mbiome_data})
    end

    @mbiome_samples = mbiome_sample_keys.map{|a| [a[0], a[1]].join('-')}
    @mbar_height = (@mbiome_samples.size > 0 ? @mbiome_samples.size * 30 + 200 : 500)

    # Microbiome/h.Pylori table (this should actually only be for GCR?)
    # Total bacterial reads in bacteria_totals; Proteobacteria reads per sample from mbiome_info
    # Total reads for Helicobacter need to come from sample_genera table
    proteobacteria_cts = mbiome_info.select{|mb| mb[:taxo_name] == 'p__Proteobacteria'}
    helicobacter_cts = SampleGenus.sample_genus_rds(@cancer_study_id, "Helicobacter")

    @hpylori_table = []
    for sample in mbiome_sample_keys
      all_rds = bacteria_totals[sample[2]]
      proteo_rds = proteobacteria_cts.select{|arr| arr[:sample_id] == sample[2]}[0].read_cts
      helico_rds = helicobacter_cts[[sample[2], 'g__Helicobacter']]

      s_hash = {patient_id: sample[3],
                sample_name: [sample[0], sample[1]].join('-'),
                sample_id: sample[2],
                all_rds: all_rds,
                proteo_rds: proteo_rds,
                p_pct: format_pct(proteo_rds, all_rds, 1),
                helico_rds: helico_rds,
                h_pct1: format_pct(helico_rds, proteo_rds, 1),
                h_pct2: format_pct(helico_rds, all_rds, 1)}
      @hpylori_table.push(s_hash)
    end

    # For immune cell tab
    immune_info = SampleImmuneCell.where({cancer_study_id: @cancer_study_id}).order(:patient_nr, :sample_type)
    @immune_samples = immune_info.map{|rec| [rec.patient_nr, rec.sample_type].join('-')}
    #@immune_tn = immune_info.pluck(:sample_type)

    @immune_perc = []
    flds = SampleImmuneCell::CIBERSORT_HDGS.keys.reverse

    for fld in flds
      @immune_perc.push({name: SampleImmuneCell::CIBERSORT_HDGS[fld],
                         data: immune_info.collect{|rec| (rec.send(fld).to_f)*100 }})
    end
    @bar_height = (@immune_samples.size > 0 ? @immune_samples.size * 30 + 200 : 500)

    @immune_hmap = []
    immune_info.each_with_index do |sample, i|
      sample_hmap = flds.collect{|fld| [flds.find_index(fld), i, sample.send(fld)]}
      @immune_hmap.push(sample_hmap)
    end
    @immune_hmap.flatten!(1)

    immune_vals = @immune_hmap.collect {|sample| sample[2]}.flatten
    @immune_hmap_max = immune_vals.max
    @immune_hmap_min = immune_vals.min  #Probably min is always zero?

    @immune_cells = flds
    #Heatmap container height = pixels per sample row, plus pixels for title and x-axis labels at top/bottom
    @hmap_height = (@immune_samples.size > 0 ? @immune_samples.size * 25 + 500 : 500)
    #@grouped_categories = grouped_categories(immune_info, 'sample_type', 'patient_nr')

    # For HLA types tab
    patient_hla_info = Patient.where({cancer_study_id: @cancer_study_id}).includes(:hla_types).references(:hla_types)
    @hla_counts = patient_hla_info.group(:hla_allele).count(:patient_id).map {|key, val| {name: key, y: val}}
    @hla_counts.reject! {|hla| hla[:name].nil?}

    @patient_hla = patient_hla_info.group_by{|patient| patient.patient_nr}
  end

  def top_gene_threshold(study_samples, nr_samples_100rank)
    ten_pct = (study_samples * 0.1).round
    return [[ten_pct, nr_samples_100rank].min(), 2].max()
  end

  def format_for_pie(patient_info, fld, sortkeys='Y')
    #patient_info.group(fld.to_sym).count(:id).map {|key, val| {name: key, y: val}}
    if sortkeys == 'Y'
      pt_sorted = patient_info.group_by {|p| p[fld.to_sym]}.sort.map{|key, val| {name: (key == 'U' ? 'NA' : key.to_s.upcase_first), y: val.size}}
    else
      pt_sorted = patient_info.group_by {|p| p[fld.to_sym]}.map{|key, val| {name: (key == 'U' ? 'NA' : key.to_s.upcase_first), y: val.size}}
    end
    pt_sorted.sort_by.with_index do |v,i|
      ["Other", "Unknown"].include?(v[:name]) ? (pt_sorted.length + i) : i
    end
  end

  def group_for_pie(patient_info, fld)
    patient_data = patient_info.reject{|patient| patient[fld.to_sym].nil? }
    if patient_data.nil? or patient_data.empty?
      patient_fld_split = []
    else
      patient_fld_split = patient_data.map {|patient| patient[fld.to_sym].split(',').map(&:strip)}.flatten
      patient_fld_split.sort.group_by { |x| x }.map { |k, v| {name: k.to_s.upcase_first, y: v.size} }
    end
  end

app/helpers/explore_study_helper.rb
module ExploreStudyHelper
  def onco_tsg(onco_flag, tsg_flag)
    if onco_flag.nil? and tsg_flag.nil?
      val = nil
    elsif onco_flag == 'Y' and tsg_flag == 'Y'
      val = 'Both'
    elsif onco_flag == 'Y'
      val = 'Onco'
    elsif tsg_flag == 'Y'
      val = 'TSG'
    else
      val = "&#10035;".html_safe
    end
  end
end

app/views/explore_studies/_clinical_info.html.erb
<div id="selector_clinical" class="btn-group">
  <button type="button" class="btn active btn-xs btn-toggle">Plots</button>
  <button type="button" class="btn btn-xs btn-toggle">Table</button>
</div>
<br />

<div id="clinical_plot_tab">
  <%= render "clinical_plots_#{study_fmt}" %>
</div>

<div id="clinical_table_tab" style="display: none">
  <div class="col-lg-12" style="margin-bottom: 25px">
    <%= render "clinical_table_#{study_fmt}" %>
  </div>
</div>

<script>
    toggleDiv('selector_clinical', 'clinical_plot_tab', 'clinical_table_tab');
</script>

app/views/explore_studies/_clinical_plots_ipg.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-lg-4" style="margin-bottom: 25px;">
      <%= tag.div id: "gender_pie_container", style: "height:150; margin: auto; min-width: 20%; max-width: 100%;", class: "",
                  data: {'title-text': "Gender", 'chart-colors': "#{PlotInfo.gender_colors}", 'chart-series': @gender_counts}  do %><% end %>
      </div>
      <div class="col-lg-4" style="margin-bottom: 25px;">
      <% na1 = @smoking_counts.find_index {|p| p[:name] == 'Unknown'} %>
      <%= tag.div id: "smoking_pie_container", style: "height:150; margin: auto; min-width: 20%; max-width: 100%;", class: "",
                  data: {'title-text': "Smoking History", 'chart-colors': "#{pie_colors(na1)}", 'chart-series': @smoking_counts}  do %><% end %>
      </div>
      <div class="col-lg-4" style="margin-bottom: 25px;">
      <% na2 = @stage_counts.find_index {|p| p[:name] == 'NA'} %>
      <%= tag.div id: "stage_pie_container", style: "height:150; margin: auto; min-width: 20%; max-width: 100%;", class: "",
                  data: {'title-text': "Tumor Stage", 'chart-colors': "#{pie_colors(na2)}", 'chart-series': @stage_counts}  do %><% end %>
      </div>
      <div class="col-lg-4" style="margin-bottom: 25px;">
      <% na3 = @site_counts.find_index {|p| p[:name] == 'Unknown'} %>
      <%= tag.div id: "site_pie_container", style: "height:150; margin: auto; min-width: 20%; max-width: 100%;", class: "",
                  data: {'title-text': "Cancer Site", 'chart-colors': "#{pie_colors(na3)}", 'chart-series': @site_counts}  do %><% end %>
      </div>
      <div class="col-lg-4" style="margin-bottom: 25px;">
      <%= tag.div id: "age_histogram_container", style: "height:150; margin: auto; min-width: 20%; max-width: 100%;", class: "",
                  data: {'title-text': "Age at Diagnosis", 'x-axis': 'Age', 'chart-series': @ages, 'bin-size': 10}  do %><% end %>
      </div>
      <div class="col-lg-4" style="margin-bottom: 25px;">
      <%= tag.div id: "survival_histogram_container", style: "height:150; margin: auto; min-width: 20%; max-width: 100%;", class: "",
                  data: {'title-text': "Survival", 'x-axis': 'Months', 'chart-series': @survival_mths, 'bin-size': 12}  do %><% end %>
      </div>
    </div>
  </div>
</div>

<script>
    explore_studies_imh()
</script>

app/views/explore_studies/_clinical_plots_tcga.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-lg-4" style="margin-bottom: 25px;">
      <%= tag.div id: "gender_pie_container", style: "height:150; margin: auto; min-width: 20%; max-width: 100%;", class: "",
                  data: {'title-text': "Gender", 'chart-colors': "#{PlotInfo.gender_colors}", 'chart-series': @gender_counts}  do %><% end %>
      </div>
      <div class="col-lg-4" style="margin-bottom: 25px;">
        <% na1 = @race_counts.find_index {|p| p[:name] == 'Unknown'} %>
        <%= tag.div id: "race_ethno_container", style: "height:150; margin: auto; min-width: 20%; max-width: 100%;", class: "",
                    data: {'title-text': "Race/Ethnicity", 'chart-colors': "#{pie_colors(na1)}", 'chart-series': @race_counts}  do %><% end %>
      </div>
      <div class="col-lg-4" style="margin-bottom: 25px;">
      <% na2 = @stage_counts.find_index {|p| p[:name] == 'Unk'} %>
      <%= tag.div id: "stage_pie_container", style: "height:150; margin: auto; min-width: 20%; max-width: 100%;", class: "",
                  data: {'title-text': "Tumor Stage", 'chart-colors': "#{pie_colors(na2)}", 'chart-series': @stage_counts}  do %><% end %>
      </div>

      <% if @site_counts.size > 1 %>
      <div class="col-lg-4" style="margin-bottom: 25px;">
      <% na3a = @site_counts.find_index {|p| p[:name] == 'Unknown'} %>
      <% na3b = @site_counts.find_index {|p| p[:name] == 'Other'} %>
      <%= tag.div id: "site_pie_container", style: "height:150; margin: auto; min-width: 20%; max-width: 100%;", class: "",
                  data: {'title-text': "Cancer Site", 'chart-colors': "#{pie_colors(na3a, na3b)}", 'chart-series': @site_counts}  do %><% end %>
      </div>
      <% end %>

      <% if @ages.any? %>
      <div class="col-lg-4" style="margin-bottom: 25px;">
      <%= tag.div id: "age_histogram_container", style: "height:150; margin: auto; min-width: 20%; max-width: 100%;", class: "",
                  data: {'title-text': "Age at Diagnosis", 'x-axis': 'Age', 'chart-series': @ages, 'bin-size': 10}  do %><% end %>
      </div>
      <% end %>

      <div class="col-lg-4" style="margin-bottom: 25px;">
      <%= tag.div id: "survival_histogram_container", style: "height:150; margin: auto; min-width: 20%; max-width: 100%;", class: "",
                  data: {'title-text': "Survival", 'x-axis': 'Months', 'chart-series': @survival_mths, 'bin-size': 12}  do %><% end %>
      </div>
    </div>
  </div>
</div>

<script>
    explore_studies_tcga()
</script>

app/views/explore_studies/_clinical_table_gcr.html.erb
<div class="table-responsive" style="padding-left: 15px; padding-right: 15px;">
<table id="clinical_table" style="width:100%" class="table table-striped table-bordered table-condensed">
 <thead>
 <tr>
   <th class="text-center">Patient</th>
   <th class="text-center">Gender</th>
   <th class="text-center">Race/Ethnicity</th>
   <th class="text-center">Family History</th>
   <th class="text-center">Smoker?</th>
   <th class="text-center">Cancer Site</th>
   <th class="text-center">Diagnosis</th>
   <th class="text-center">Diagnosis Subtype</th>
   <th class="text-center">Differentiation</th>
 </tr>
 </thead>
 <tbody>
 <% @patient_data.each do |patient| %>
     <tr>
       <td class="text-center"><%= link_to patient.patient_nr, sample_query_path(patient_id: patient.id, cancer_studies: [patient.cancer_study_id]) %></td>
       <td class="text-center"><%= patient.gender %></td>
       <td class="text-center"><%= patient.race_ethnicity %></td>
       <td class="text-center"><%= patient.gc_history %></td>
       <td class="text-center"><%= patient.smoking_history %></td>
       <td class="text-center"><%= patient.cancer_site_dtl %></td>
       <td class="text-center"><%= patient.diagnosis %></td>
       <td class="text-center"><%= patient.diagnosis_subtype %></td>
       <td class="text-center"><%= patient.differentiation %></td>
     </tr>
 <% end %>
 </tbody>
</table>
</div>

<script>
    $("#clinical_table").DataTable();
</script>

app/views/explore_studies/_clinical_table_ipg.html.erb
<div class="table-responsive" style="padding-left: 15px; padding-right: 15px;">
<table id="clinical_table" style="width:100%" class="table table-striped table-bordered table-condensed">
 <thead>
 <tr>
   <th class="text-center">Patient</th>
   <th class="text-center">Gender</th>
   <th class="text-center">Race</th>
   <th class="text-center">Age</th>
   <th class="text-center">BMI</th>
   <th class="text-center">Smoker?</th>
   <th class="text-center">Cancer Site</th>
   <th class="text-center">Site Dtl</th>
   <th class="text-center">Cancer Grade</th>
   <th class="text-center">Tumor Stage</th>
   <th class="text-center">Recur?</th>
   <th class="text-center">Days Survival</th>
 </tr>
 </thead>
 <tbody>
 <% @patient_data.each do |patient| %>
     <tr>
       <td class="text-center"><%= link_to patient.patient_nr, sample_query_path(patient_id: patient.id, cancer_studies: [patient.cancer_study_id]) %></td>
       <td class="text-center"><%= patient.gender %></td>
       <td class="text-center"><%= patient.race_ethnicity %></td>
       <td class="text-center"><%= patient.dx_age %></td>
       <td class="text-center"><%= patient.dx_bmi %></td>
       <td class="text-center"><%= patient.smoking_history %></td>
       <td class="text-center"><%= patient.cancer_site %></td>
       <td class="text-center"><%= patient.cancer_site_dtl %></td>
       <td class="text-center"><%= patient.cancer_grade %></td>
       <td class="text-center"><%= patient.summary_stage %></td>
       <td class="text-center"><%= patient.recurrence %></td>
       <td class="text-center"><%= patient.days_survival %></td>
     </tr>
 <% end %>
 </tbody>
</table>
</div>

<script>
    $("#clinical_table").DataTable();
</script>

app/views/explore_studies/_clinical_table_tcga.html.erb
<div class="table-responsive" style="padding-left: 15px; padding-right: 15px;">
<table id="clinical_table" style="width:100%" class="table table-striped table-bordered table-condensed">
 <thead>
 <tr>
   <th class="text-center">Patient</th>
   <th class="text-center">Gender</th>
   <th class="text-center">Race/Ethnicity</th>
   <th class="text-center">Age</th>
   <th class="text-center">BMI</th>
   <th class="text-center">Diagnosis</th>
   <th class="text-center">Cancer Site</th>
   <th class="text-center">Tumor Stage</th>
   <th class="text-center">Recur?</th>
   <th class="text-center">Days Survival</th>
 </tr>
 </thead>
 <tbody>
 <% @patient_data.each do |patient| %>
     <tr>
       <td class="text-center"><%= link_to patient.patient_nr, sample_query_path(patient_id: patient.id, cancer_studies: [patient.cancer_study_id]) %></td>
       <td class="text-center"><%= patient.gender %></td>
       <td class="text-center"><%= patient.race_ethnicity %></td>
       <td class="text-center"><%= patient.dx_age %></td>
       <td class="text-center"><%= patient.dx_bmi %></td>
       <td class="text-center"><%= patient.diagnosis %></td>
       <td class="text-center"><%= patient.cancer_site %></td>
       <td class="text-center"><%= patient.summary_stage %></td>
       <td class="text-center"><%= patient.recurrence %></td>
       <td class="text-center"><%= patient.days_survival_or_na %></td>
     </tr>
 <% end %>
 </tbody>
</table>
</div>

<script>
    $("#clinical_table").dataTable();
</script>

app/views/explore_studies/_hla_table.html.erb
<div class="col-lg-4" style="margin-bottom: 25px">
  <% hla_alleles = hla_counts.sum {|hla| hla[:y]} %>
  <div class="container">
    <table id="hla_<%=hla_gene.downcase%>_table" style="margin-left:auto; margin-right:auto" class="table table-striped table-bordered table-condensed">
      <thead>
      <tr>
        <th class="text-center">HLA-<%= hla_gene %></th>
        <th class="text-center">Count</th>
        <th class="text-center">%</th>
      </tr>
      </thead>
      <tbody>
      <% hla_counts.each do |hla| %>
        <tr>
          <td class="text-center"><%= hla[:name] %></td>
          <td class="text-center"><%= hla[:y] %></td>
          <td class="text-center"><%= format_pct(hla[:y], hla_alleles, 1)%></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/explore_studies/_immune_info.html.erb
<div id="selector_immune" class="btn-group">
  <button type="button" class="btn active btn-xs btn-toggle">Heatmap</button>
  <button type="button" class="btn btn-xs btn-toggle">Barplot</button>
</div>
<br />

<div id="immune_hmap_tab">
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="row">
        <%= tag.div id: "immune_hmap_container", style: "margin: auto; min-width: 100%; max-width: 100%; height: #{@hmap_height}px;", class: "",
                    data: {'title-text': "Immune Infiltrates", 'x-categories': @immune_samples, 'y-categories': @immune_cells,
                           'chart-series': @immune_hmap, 'hmap-min': @immune_hmap_min, 'hmap-max': @immune_hmap_max }  do %><% end %>
      </div>
    </div>
  </div>
</div>

<div id="immune_bar_tab" style="display:none">
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <%= tag.div id: "immune_chart_container", style: "height:#{@bar_height}px; margin: auto; min-width: 100%; max-width: 100%;", class: "",
                  data: {'title-text': "Immune Infiltrates", 'chart-colors': "#{PlotInfo::PLOT_COLORS[:cibersort_22]}",
                         'x-categories': @immune_samples, 'chart-series': @immune_perc}  do %><% end %>
    </div>
  </div>
</div>
</div>

<script>
    toggleDiv('selector_immune', 'immune_hmap_tab', 'immune_bar_tab')
</script>

app/views/explore_studies/_mbiome_info.html.erb
<% if Portal::Config::Info['project'] == "gcr" %>
  <div id="selector_mbiome" class="btn-group">
    <button type="button" class="btn active btn-xs btn-toggle">Overview</button>
    <button type="button" class="btn btn-xs btn-toggle">H. pylori</button>
  </div>
  <br />
<% end %>

<div id="mbiome_plot_tab" class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <%= tag.div id: "mbiome_chart_container", style:"height:#{@mbar_height}px; margin: auto; min-width: 100%; max-width: 100%;", class: "",
                  data: {'title-text': "Microbiome Composition", 'chart-colors': "#{@mbiome_colors}",
                         'x-categories': @mbiome_samples, 'chart-series': @mbiome_perc}  do %><% end %>
    </div>
  </div>
</div>

<% if Portal::Config::Info['project'] == "gcr" %>
  <div id="mbiome_table_tab" style="display: none">
    <div class="col-lg-8" style="margin-bottom: 25px">
      <%= render "mbiome_table" %>
    </div>
  </div>

  <script>
    toggleDiv('selector_mbiome', 'mbiome_plot_tab', 'mbiome_table_tab');
  </script>
<% end %>