config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords'
      }

  root to: 'welcome#index', via: [:get, :post]
  match 'param_entry', to: 'welcome#param_inputs', via: [:get, :post]

  match 'contact', to: 'static_pages#contact', via: 'get'
  match 'project_overview', to: 'static_pages#project_overview', via: 'get'
  match 'data_release', to: 'static_pages#data_release', via: 'get'
  match 'user_signup', to: 'static_pages#user_signup', via: 'get'

  match 'study_query', to: 'study_queries#index', via: [:get, :post]
  match 'study_explore', to: 'explore_studies#index', via: [:get, :post]

  match 'gene_summary', to: 'gene_summaries#index', via: [:get, :post]

  match 'neoantigen_query', to: 'neoantigen_queries#index', via: [:get, :post]

  match 'sample_query', to: 'sample_queries#index', via: [:get, :post]
  get 'get_gene_expr_data', to: 'sample_queries#get_gene_expr_data'

  

end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<div style="margin-top: 20px;">
<footer class="sticky-footer">
  <!-- Footer Links -->
  <div class="container-fluid text-center">
    <!-- Grid row -->
    <div class="row">
      Copyright © 2020 CancerGenomePortal Project - Stanford School of Medicine - Ji Research Group |
      <%= link_to "Terms of Use", 'https://www.stanford.edu/site/terms/', target: :_blank %> |
      <%= link_to "Privacy", 'https://www.stanford.edu/site/privacy/', target: :_blank %>
    </div>

    <% if Portal::Config::Info['footer_image'] %>
    <div class="row" style="margin-top: -20px">
      <%= link_to image_tag("ji_research_group_logo.png", width:"300", class: "img", style: "margin-left: 3px; margin-bottom: -10px;"), 'https://dna-discovery.stanford.edu/', target: :_blank %>
      <%= link_to image_tag(Portal::Config::Info['footer_image'], width:"220", class: "img", style: "margin-left: 3px; margin-bottom: -19px;"), Portal::Config::Info['footer_href'], target: :_blank %>
    </div>

    <% else %>
    <%= link_to image_tag("ji_research_group_logo.png", width:"300", class: "img", style: "margin-left: 3px; margin-bottom: -10px;"), 'https://dna-discovery.stanford.edu/', target: :_blank %>
    <% end %>

  </div>
</footer>
</div>

app/views/layouts/_header.html.erb
<header style="margin-bottom: 50px">
  <nav class="navbar navbar-top" role="navigation" style="color: black;">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <%= link_to image_tag(Portal::Config::Info['favicon'], alt: "Brand"), root_path, :class=>'navbar-brand' %>
        <%= link_to Portal::Config::Info['base_title'], root_path, class: 'navbar-brand', style: 'font-size: 24px; margin-left: 5px; align-items: center; display: flex; color: white;' %>
      </div>

      <%= link_to image_tag(Portal::Config::Info['header_image'], alt: "Brand"), Portal::Config::Info['header_href'], :class=>'navbar-brand navbar-imh', target: :_blank %>
      <% if Portal::Config::Info['login_required'] %>
        <%= render 'layouts/navbar_hdr_login' %>
      <% else %>
        <%= render 'layouts/navbar_hdr_info' %>
      <% end %>

    </div><!-- /.container-fluid -->
  </nav>
  <% if Portal::Config::Info['project'] == 'gcr' %>
    <div class="release-notes">Data release <%= Cohort.latest_release[0] %> (<%= Cohort.latest_release[1].strftime("%b %Y") %>)</div>
  <% end %>
</header>

app/views/layouts/_navbar_hdr_info.html.erb
<ul class="nav navbar-nav navbar-right" style="font-size:28px;color:white;">
  <li style="font-size:28px; color:white;"><%= link_to "Project overview",  project_overview_path, class:(request.fullpath == project_overview_path ? "selected" : '') %></li>
  <li style="font-size:28px; color:white;"><%= link_to "Data releases",  data_release_path, class:(request.fullpath == data_release_path ? "selected" : '') %></li>
  <li style="font-size:28px; color:white;"><%= link_to "Contact", contact_path, class:(request.fullpath == contact_path ? "selected" : '') %></li>
</ul>

app/views/layouts/_navbar_hdr_login.html.erb
<% if user_signed_in? %>
  <ul class="nav navbar-nav navbar-right">

    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="font-size: 20px;">Project info <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to "Project overview",  project_overview_path, class:(request.fullpath == project_overview_path ? "selected" : ''), style: 'font-size: 16px; color: black; font-weight: normal;' %></li>
        <li><%= link_to "Data releases",  data_release_path, class:(request.fullpath == data_release_path ? "selected" : ''), style: 'font-size: 16px; color: black; font-weight: normal;' %></li>
        <li><%= link_to "Contact", contact_path, class:(request.fullpath == contact_path ? "selected" : ''), style: 'font-size: 16px; color: black; font-weight: normal;' %></li>
      </ul>
    </li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="font-size: 20px;"><%= current_user.email %> <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to 'Edit user profile', edit_user_registration_path, style:'font-size: 16px; color: black; font-weight: normal;' %></li>
        <li role="separator" class="divider"></li>
        <li><%= link_to 'Log out', destroy_user_session_path, method: :delete, style:'font-size: 16px; color: black; font-weight: normal;' %></li>
      </ul>
    </li>
  </ul>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="html-page">
  <head>

    <title><%= full_title(yield(:title)) %></title>



    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= favicon_link_tag asset_path(Portal::Config::Info['favicon']) %>

    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body data-controller="<%=controller_name%>" data-action="<%=action_name%>" class="<%= controller.controller_name %> body-page">

  <%= render 'layouts/header' %>

  <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
  </div>
  </body>
</html>